# Generated by Django 4.1.5 on 2023-01-30 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                ("food_num", models.BigAutoField(primary_key=True, serialize=False)),
                ("food_name", models.CharField(max_length=200)),
                ("price", models.IntegerField(default=0)),
                ("food_explain", models.TextField(blank=True, max_length=2000)),
                ("category", models.CharField(max_length=250)),
                ("image", models.ImageField(blank=True, upload_to="static/menuimg/")),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("active", models.BooleanField(default=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.list"
                    ),
                ),
            ],
            options={
                "db_table": "CartItem",
            },
        ),
    ]
